development:
  adapter: postgresql
  host: localhost
  database: cubic
  username: erik
  password: 3r1k0db

test:
  adapter: postgresql
  host: localhost
  database: nscout_test
  template: cubic
  username: erik
  password: 3r1k0db

production:
  adapter: postgresql
  host: localhost
  database: cubic
  username: erik
  password: 3r1k0db
